const fs = require('fs');

const raw30Cards = [
  {
    id: "30th-012",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "012/158",
    nameEs: "Ho-Oh",
    nameEn: "Ho-Oh",
    elementType: "Fuego",
    subType: "Básico",
    hp: 130,
    rarity: "Rara",
    artist: "Mitsuhiro Arita",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-012-mt77r0fm-high.webp?v=1787574580642",
    stage: "Básico",
    marketPrice: "12,50 €",
    attacks: [
      { name: "Aliento Sagrado", cost: ["Fuego"], damage: "", description: "Descarta todas las Energías de este Pokémon. Cura todos los puntos de daño a uno de tus Pokémon en Banca." },
      { name: "Ala Ígnea", cost: ["Fuego", "Fuego", "Incoloro"], damage: "100", description: "" }
    ],
    weakness: "Rayo x2",
    retreatCost: 2,
    flavorText: "El ave legendaria del arcoíris con el sello oficial del 30 Aniversario.",
    isSecret: false
  },
  {
    id: "30th-021",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "021/158",
    nameEs: "Greninja ex",
    nameEn: "Greninja ex",
    elementType: "Agua",
    subType: "ex",
    hp: 300,
    rarity: "Doble Rara ex",
    artist: "5ban Graphics",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-021-high.webp?v=1780504959418",
    stage: "Fase 2",
    marketPrice: "75,00 €",
    attacks: [
      { name: "Tajo Sigiloso", cost: ["Agua"], damage: "20", description: "Este ataque hace 20 puntos de daño a uno de los Pokémon de tu rival por cada contador de daño en ese Pokémon." },
      { name: "Filo Agua", cost: ["Agua", "Agua", "Incoloro"], damage: "160", description: "" }
    ],
    weakness: "Rayo x2",
    retreatCost: 1,
    flavorText: "Edición conmemorativa estrella dorada con acabados holográficos prémium.",
    isSecret: false
  },
  {
    id: "30th-023",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "023/158",
    nameEs: "Pikachu (Impactrueno)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "OKACHEKE",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-023-mt77r9v0-high.webp?v=1787574592749",
    stage: "Básico",
    marketPrice: "8,50 €",
    attacks: [
      { name: "Impactrueno", cost: ["Rayo"], damage: "20", description: "Lanza 1 moneda. Si sale cara, el Pokémon Activo de tu rival pasa a estar Paralizado." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "1 de las 30 ilustraciones exclusivas de Pikachu para el 30 Aniversario.",
    isSecret: false
  },
  {
    id: "30th-025",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "025/158",
    nameEs: "Pikachu (Chispa)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Yuu Nishida",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-025-mt77rpv0-high.webp?v=1787574613517",
    stage: "Básico",
    marketPrice: "9,00 €",
    attacks: [
      { name: "Chispa", cost: ["Rayo", "Incoloro"], damage: "20", description: "Este ataque también hace 20 puntos de daño a uno de los Pokémon en Banca de tu rival." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Ilustración primaveral cálida con el sello del 30 Aniversario.",
    isSecret: false
  },
  {
    id: "30th-026",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "026/158",
    nameEs: "Pikachu (Curiosear)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Atsuko Nishida",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-026-mt77rwru-high.webp?v=1787574622380",
    stage: "Básico",
    marketPrice: "14,00 €",
    attacks: [
      { name: "Curiosear", cost: ["Incoloro"], damage: "", description: "Tu rival enseña las cartas de su mano." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Diseñado por la creadora original del aspecto de Pikachu, Atsuko Nishida.",
    isSecret: false
  },
  {
    id: "30th-028",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "028/158",
    nameEs: "Pikachu (Mirada Solitaria)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "Tomokazu Komiya",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-028-msyak829-high.webp?v=1787035105857",
    stage: "Básico",
    marketPrice: "7,80 €",
    attacks: [
      { name: "Habilidad: Mirada Solitaria", cost: [], damage: "", description: "Mientras este Pokémon esté en el Puesto Activo, los ataques del rival hacen 20 puntos de daño menos." },
      { name: "Pika Ball", cost: ["Rayo", "Incoloro"], damage: "20", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Estilo artístico inconfundible con gran detalle expresivo.",
    isSecret: false
  },
  {
    id: "30th-030",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "030/158",
    nameEs: "Pikachu (Rayo)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "Mitsuhiro Arita",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-030-mt77s5f5-high.webp?v=1787574633715",
    stage: "Básico",
    marketPrice: "16,50 €",
    attacks: [
      { name: "Rayo Eléctrico", cost: ["Rayo"], damage: "30", description: "Lanza 1 moneda. Si sale cruz, este ataque no hace nada." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "El ilustrador de las cartas Base originales rinde tributo a los 30 años de TCG.",
    isSecret: false
  },
  {
    id: "30th-032",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "032/158",
    nameEs: "Pikachu (Ken Sugimori)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 50,
    rarity: "Rara",
    artist: "Ken Sugimori",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-032-mt77sdg6-high.webp?v=1787574644187",
    stage: "Básico",
    marketPrice: "11,00 €",
    attacks: [
      { name: "Roer", cost: ["Incoloro"], damage: "10", description: "" },
      { name: "Trueno Clásico", cost: ["Rayo", "Incoloro"], damage: "30", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "El diseño original de 1996 de Ken Sugimori en acabado holo 30 aniversario.",
    isSecret: false
  },
  {
    id: "30th-033",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "033/158",
    nameEs: "Pikachu (A Escondidas)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "HYOGONOSUKE",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-033-mt77slp1-high.webp?v=1787574654751",
    stage: "Básico",
    marketPrice: "8,20 €",
    attacks: [
      { name: "Habilidad: A Escondidas", cost: [], damage: "", description: "Mientras este Pokémon esté en tu Banca, evita todo el daño de ataques infligido a este Pokémon." },
      { name: "Chispazo", cost: ["Rayo"], damage: "20", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Un tierno Pikachu jugando entre flores primaverales.",
    isSecret: false
  },
  {
    id: "30th-034",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "034/158",
    nameEs: "Pikachu (Bosque)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Kouki Saitou",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-034-mt77stir-high.webp?v=1787574664945",
    stage: "Básico",
    marketPrice: "7,50 €",
    attacks: [
      { name: "Impacto Rápido", cost: ["Rayo"], damage: "20", description: "" },
      { name: "Electrocola", cost: ["Rayo", "Incoloro"], damage: "40", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu sonriente saltando de emoción.",
    isSecret: false
  },
  {
    id: "30th-036",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "036/158",
    nameEs: "Pikachu (Escalera)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Shinji Kanda",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-036-high.webp?v=1780505024306",
    stage: "Básico",
    marketPrice: "12,00 €",
    attacks: [
      { name: "Mirada Electrizante", cost: ["Rayo"], damage: "20", description: "El rival no puede jugar Partidarios durante su próximo turno." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Estilo de trazos expresivos y contrastes intensos.",
    isSecret: false
  },
  {
    id: "30th-037",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "037/158",
    nameEs: "Pikachu (Cola Energética)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "PLANETA Igarashi",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-037-high.webp?v=1780505020316",
    stage: "Básico",
    marketPrice: "7,90 €",
    attacks: [
      { name: "Cola Energética", cost: ["Rayo"], damage: "20", description: "Une 1 Energía Rayo Básica de tu pila de descartes a este Pokémon." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu cargando su cola con chispas doradas.",
    isSecret: false
  },
  {
    id: "30th-038",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "038/158",
    nameEs: "Pikachu (Electropelota)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "Naoki Saito",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-038-mt77t17o-high.webp?v=1787574674988",
    stage: "Básico",
    marketPrice: "15,00 €",
    attacks: [
      { name: "Electropelota", cost: ["Rayo"], damage: "30", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "El aclamado estilo vibrante de Naoki Saito.",
    isSecret: false
  },
  {
    id: "30th-039",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "039/158",
    nameEs: "Pikachu (Chispa Relámpago)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "kirisAki",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-039-mt77t88c-high.webp?v=1787574683988",
    stage: "Básico",
    marketPrice: "8,00 €",
    attacks: [
      { name: "Chispa Relámpago", cost: ["Rayo"], damage: "20+", description: "Si este Pokémon tiene alguna Energía Especial unida, hace 30 más de daño." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu destellando relámpagos con gran determinación.",
    isSecret: false
  },
  {
    id: "30th-040",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "040/158",
    nameEs: "Pikachu (Danza Trueno)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Taira Akitsu",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-040-mt77tee0-high.webp?v=1787574693605",
    stage: "Básico",
    marketPrice: "6,80 €",
    attacks: [
      { name: "Danza Trueno", cost: ["Rayo", "Incoloro"], damage: "30", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu bailando alegremente en el festival del 30 Aniversario.",
    isSecret: false
  },
  {
    id: "30th-041",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "041/158",
    nameEs: "Pikachu (Placaje Eléctrico)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "sowsow",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-041-mt77tmm1-high.webp?v=1787574702559",
    stage: "Básico",
    marketPrice: "9,50 €",
    attacks: [
      { name: "Placaje Eléctrico", cost: ["Rayo", "Rayo"], damage: "50", description: "Este Pokémon se hace 10 puntos de daño a sí mismo." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Estilo artístico en acuarela suave con tonos cálidos.",
    isSecret: false
  },
  {
    id: "30th-042",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "042/158",
    nameEs: "Pikachu (Pika Amistad)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "Yuka Morii",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-042-msyakdr8-high.webp?v=1787035113366",
    stage: "Básico",
    marketPrice: "10,20 €",
    attacks: [
      { name: "Pika Amistad", cost: ["Incoloro"], damage: "", description: "Busca en tu baraja 1 Pokémon Básico y ponlo en tu Banca." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Escultura en plastilina hecha a mano por la célebre Yuka Morii.",
    isSecret: false
  },
  {
    id: "30th-043",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "043/158",
    nameEs: "Pikachu (Carga Rayo)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "GIDORA",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-043-mt77ttks-high.webp?v=1787574711606",
    stage: "Básico",
    marketPrice: "7,00 €",
    attacks: [
      { name: "Carga Rayo", cost: ["Rayo"], damage: "20", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu en guardia acumulando energía en sus mejillas rojas.",
    isSecret: false
  },
  {
    id: "30th-044",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "044/158",
    nameEs: "Pikachu (Electrochoque)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "sui",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-044-mt77u00r-high.webp?v=1787574719995",
    stage: "Básico",
    marketPrice: "8,50 €",
    attacks: [
      { name: "Electrochoque", cost: ["Rayo", "Incoloro"], damage: "30", description: "Lanza 1 moneda. Si sale cara, el rival pasa a estar Paralizado." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Ilustración con contrastes de luz y sombra de gran impacto visual.",
    isSecret: false
  },
  {
    id: "30th-047",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "047/158",
    nameEs: "Pikachu (Pika Saludo)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 60,
    rarity: "Rara",
    artist: "Sanosuke Sakuma",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-047-high.webp?v=1780505016067",
    stage: "Básico",
    marketPrice: "8,00 €",
    attacks: [
      { name: "Pika Saludo", cost: ["Incoloro"], damage: "20", description: "Roba 1 carta de tu baraja." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Un Pikachu amigable saludando a todos los entrenadores del mundo.",
    isSecret: false
  },
  {
    id: "30th-049",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "049/158",
    nameEs: "Pikachu (Cola Férrea)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Akira Komayama",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-049-mt77ugk8-high.webp?v=1787574741414",
    stage: "Básico",
    marketPrice: "7,80 €",
    attacks: [
      { name: "Cola Férrea", cost: ["Incoloro", "Incoloro"], damage: "30x", description: "Lanza 3 monedas. Hace 30 de daño por cada cara." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Un ataque contundente con cola endurecida.",
    isSecret: false
  },
  {
    id: "30th-050",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "050/158",
    nameEs: "Pikachu (Chispa Festiva)",
    nameEn: "Pikachu",
    elementType: "Rayo",
    subType: "Básico",
    hp: 70,
    rarity: "Rara",
    artist: "Shibuzoh.",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-050-msyakk7t-high.webp?v=1787035121534",
    stage: "Básico",
    marketPrice: "8,90 €",
    attacks: [
      { name: "Chispa Festiva", cost: ["Rayo"], damage: "20+", description: "Si tienes 3 o más cartas en tu Banca, este ataque hace 20 más de daño." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Celebración con confeti y destellos de alegría.",
    isSecret: false
  },
  {
    id: "30th-053",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "053/158",
    nameEs: "Pikachu ex",
    nameEn: "Pikachu ex 30th",
    elementType: "Rayo",
    subType: "ex",
    hp: 200,
    rarity: "Doble Rara ex",
    artist: "5ban Graphics",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-053-mt77undl-high.webp?v=1787574750230",
    stage: "Básico",
    marketPrice: "18,50 €",
    attacks: [
      { name: "Carga Acelerada", cost: ["Rayo"], damage: "40", description: "Une 2 Energías Rayo de tu baraja a tus Pokémon en banca." },
      { name: "Rayo Fulgor 30th", cost: ["Rayo", "Rayo", "Incoloro"], damage: "220", description: "Descarta 1 Energía de este Pokémon." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "La versión ex insignia de la colección Celebración 30 Aniversario.",
    isSecret: false
  },
  {
    id: "30th-054",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "054/158",
    nameEs: "Pikachu ex (Ultra Rara)",
    nameEn: "Pikachu ex Full Art 30th",
    elementType: "Rayo",
    subType: "ex",
    hp: 220,
    rarity: "Ultra Rara",
    artist: "PLANETA Mochizuki",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-054-mt77utpc-high.webp?v=1787574759379",
    stage: "Básico",
    marketPrice: "38,00 €",
    attacks: [
      { name: "Rayo Celestial", cost: ["Rayo", "Incoloro"], damage: "120", description: "" },
      { name: "Impactrueno Máximo", cost: ["Rayo", "Rayo", "Rayo"], damage: "250", description: "Descarta 2 Energías." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Arte completo holográfico con relieve texturizado.",
    isSecret: false
  },
  {
    id: "30th-069",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "069/158",
    nameEs: "Espeon",
    nameEn: "Espeon 30th",
    elementType: "Psíquico",
    subType: "Fase 1",
    hp: 110,
    rarity: "Rara",
    artist: "Atsushi Furusawa",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-069-high.webp?v=1780505009805",
    stage: "Fase 1",
    marketPrice: "8,90 €",
    attacks: [
      { name: "Psicocarga Solar", cost: ["Psíquico", "Incoloro"], damage: "80", description: "Cura 30 puntos de daño a este Pokémon." }
    ],
    weakness: "Oscura x2",
    retreatCost: 1,
    flavorText: "La evolución de Eevee bañada por la luz del sol en celebración de tres décadas.",
    isSecret: false
  },
  {
    id: "30th-071",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "071/158",
    nameEs: "Sylveon ex",
    nameEn: "Sylveon ex 30th",
    elementType: "Psíquico",
    subType: "ex",
    hp: 270,
    rarity: "Doble Rara ex",
    artist: "PLANETA Yamashita",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-071-high.webp?v=1780505004258",
    stage: "Fase 1",
    marketPrice: "24,00 €",
    attacks: [
      { name: "Viento Feérico Dulce", cost: ["Psíquico"], damage: "60", description: "Roba 2 cartas de tu baraja." },
      { name: "Fuerza Mágica Espectral", cost: ["Psíquico", "Incoloro", "Incoloro"], damage: "190", description: "El rival queda Confundido." }
    ],
    weakness: "Metal x2",
    retreatCost: 2,
    flavorText: "Los lazos de Sylveon envuelven el corazón de los entrenadores.",
    isSecret: false
  },
  {
    id: "30th-089",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "089/158",
    nameEs: "Meowth de Alola",
    nameEn: "Alolan Meowth 30th",
    elementType: "Oscura",
    subType: "Básico",
    hp: 70,
    rarity: "Común",
    artist: "Kouki Saitou",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-089-msyakqxc-high.webp?v=1787035130226",
    stage: "Básico",
    marketPrice: "3,20 €",
    attacks: [
      { name: "Arañazo Sombrío", cost: ["Oscura"], damage: "20", description: "" }
    ],
    weakness: "Planta x2",
    retreatCost: 1,
    flavorText: "Orgulloso y refinado, este Meowth de Alola celebra las tres décadas.",
    isSecret: false
  },
  {
    id: "30th-091",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "091/158",
    nameEs: "Umbreon",
    nameEn: "Umbreon 30th",
    elementType: "Oscura",
    subType: "Fase 1",
    hp: 110,
    rarity: "Rara",
    artist: "Mitsuhiro Arita",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-091-high.webp?v=1780504999157",
    stage: "Fase 1",
    marketPrice: "14,50 €",
    attacks: [
      { name: "Mordisco Nocturno", cost: ["Oscura", "Incoloro"], damage: "90", description: "Descarta 1 Energía del rival." }
    ],
    weakness: "Planta x2",
    retreatCost: 1,
    flavorText: "Bajo la luna llena, los anillos dorados de Umbreon resplandecen.",
    isSecret: false
  },
  {
    id: "30th-113",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "113/158",
    nameEs: "Meowth",
    nameEn: "Meowth 30th",
    elementType: "Incoloro",
    subType: "Básico",
    hp: 70,
    rarity: "Común",
    artist: "Ken Sugimori",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-113-msyal2l1-high.webp?v=1787035145332",
    stage: "Básico",
    marketPrice: "2,80 €",
    attacks: [
      { name: "Día de Pago", cost: ["Incoloro"], damage: "10", description: "Roba 1 carta de tu baraja." },
      { name: "Golpe Moneda", cost: ["Incoloro", "Incoloro"], damage: "30", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Le fascinan los objetos brillantes y redondos.",
    isSecret: false
  },
  {
    id: "30th-116",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "116/158",
    nameEs: "Eevee",
    nameEn: "Eevee 30th",
    elementType: "Incoloro",
    subType: "Básico",
    hp: 70,
    rarity: "Común",
    artist: "Yuu Nishida",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-116-high.webp?v=1782883164803",
    stage: "Básico",
    marketPrice: "4,50 €",
    attacks: [
      { name: "Amigos de Evolución", cost: ["Incoloro"], damage: "", description: "Busca en tu baraja una evolución de Eevee y ponla en tu mano." },
      { name: "Placaje", cost: ["Incoloro", "Incoloro"], damage: "30", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Un Pokémon con un ADN irregular capaz de adaptarse a múltiples formas.",
    isSecret: false
  },
  {
    id: "30th-121",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "121/158",
    nameEs: "Lugia",
    nameEn: "Lugia 30th",
    elementType: "Incoloro",
    subType: "Básico",
    hp: 130,
    rarity: "Rara",
    artist: "kawayoo",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-121-mt77v0nq-high.webp?v=1787574767365",
    stage: "Básico",
    marketPrice: "16,00 €",
    attacks: [
      { name: "Aerochorro Supremo", cost: ["Incoloro", "Incoloro", "Incoloro", "Incoloro"], damage: "140", description: "Descarta 1 Energía de este Pokémon." }
    ],
    weakness: "Rayo x2",
    retreatCost: 2,
    flavorText: "El guardián de los mares que mora en las profundidades de las Islas Remolino.",
    isSecret: false
  },
  {
    id: "30th-131",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "131/158",
    nameEs: "Lapras (Rara Ilustración)",
    nameEn: "Lapras (Illustration Rare)",
    elementType: "Agua",
    subType: "Básico",
    hp: 130,
    rarity: "Rara Ilustración",
    artist: "HYOGONOSUKE",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-131-high.webp?v=1780504993481",
    stage: "Básico",
    marketPrice: "22,00 €",
    attacks: [
      { name: "Navegación Serena", cost: ["Agua"], damage: "", description: "Cura 40 puntos de daño a todos tus Pokémon de tipo Agua." },
      { name: "Hidrobomba Oceánica", cost: ["Agua", "Agua", "Incoloro"], damage: "110", description: "" }
    ],
    weakness: "Rayo x2",
    retreatCost: 2,
    flavorText: "Surca aguas cristalinas en una puesta de sol inolvidable.",
    isSecret: true
  },
  {
    id: "30th-136",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "136/158",
    nameEs: "Drifloon (Rara Ilustración)",
    nameEn: "Drifloon (Illustration Rare)",
    elementType: "Psíquico",
    subType: "Básico",
    hp: 70,
    rarity: "Rara Ilustración",
    artist: "Tomokazu Komiya",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-136-high.webp?v=1780504987675",
    stage: "Básico",
    marketPrice: "18,00 €",
    attacks: [
      { name: "Vuelo Nocturno", cost: ["Psíquico"], damage: "30", description: "" }
    ],
    weakness: "Oscura x2",
    retreatCost: 1,
    flavorText: "Flota tranquilamente en el cielo del atardecer.",
    isSecret: true
  },
  {
    id: "30th-138",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "138/158",
    nameEs: "Lycanroc (Rara Ilustración)",
    nameEn: "Lycanroc (Illustration Rare)",
    elementType: "Lucha",
    subType: "Fase 1",
    hp: 120,
    rarity: "Rara Ilustración",
    artist: "Shinji Kanda",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-138-low.webp?v=1780504982084",
    stage: "Fase 1",
    marketPrice: "16,50 €",
    attacks: [
      { name: "Roca Afilada Salvaje", cost: ["Lucha", "Incoloro"], damage: "90", description: "" }
    ],
    weakness: "Planta x2",
    retreatCost: 2,
    flavorText: "Aúlla a la luna crepuscular con mirada desafiante.",
    isSecret: true
  },
  {
    id: "30th-139",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "139/158",
    nameEs: "Meowth de Alola (Rara Ilustración)",
    nameEn: "Alolan Meowth (Illustration Rare)",
    elementType: "Oscura",
    subType: "Básico",
    hp: 70,
    rarity: "Rara Ilustración",
    artist: "HYOGONOSUKE",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-139-msyalb08-high.webp?v=1787035156424",
    stage: "Básico",
    marketPrice: "17,00 €",
    attacks: [
      { name: "Astucia Felina", cost: ["Oscura"], damage: "30", description: "" }
    ],
    weakness: "Planta x2",
    retreatCost: 1,
    flavorText: "Descansando elegantemente en una terraza tropical.",
    isSecret: true
  },
  {
    id: "30th-144",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "144/158",
    nameEs: "Meowth (Rara Ilustración)",
    nameEn: "Meowth (Illustration Rare)",
    elementType: "Incoloro",
    subType: "Básico",
    hp: 70,
    rarity: "Rara Ilustración",
    artist: "miki kudo",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-144-msyalhag-high.webp?v=1787035164628",
    stage: "Básico",
    marketPrice: "21,00 €",
    attacks: [
      { name: "Moneda de Oro Brillante", cost: ["Incoloro"], damage: "40", description: "Roba 2 cartas." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Meowth jugando con una brillante moneda en su habitación.",
    isSecret: true
  },
  {
    id: "30th-145",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "145/158",
    nameEs: "Zorua de Hisui (Rara Ilustración)",
    nameEn: "Hisuian Zorua (Illustration Rare)",
    elementType: "Psíquico",
    subType: "Básico",
    hp: 60,
    rarity: "Rara Ilustración",
    artist: "miki kudo",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-145-high.webp?v=1780504976581",
    stage: "Básico",
    marketPrice: "19,50 €",
    attacks: [
      { name: "Ilusión Rencorosa", cost: [], damage: "", description: "Busca en tu baraja 2 cartas de Pokémon y ponlas en tu mano. No cuesta Energía." }
    ],
    weakness: "Oscura x2",
    retreatCost: 1,
    flavorText: "Un espíritu que vaga en la nieve de la antigua región de Hisui.",
    isSecret: true
  },
  {
    id: "30th-149",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "149/158",
    nameEs: "Pikachu ex (Rara Ilustración Especial - SIR)",
    nameEn: "Pikachu ex (Special Illustration Rare)",
    elementType: "Rayo",
    subType: "ex",
    hp: 200,
    rarity: "Rara Ilustración Especial",
    artist: "Mitsuhiro Arita",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-149-msyamb9y-high.webp?v=1787035203546",
    stage: "Básico",
    marketPrice: "185,00 €",
    attacks: [
      { name: "Rayo de Fiesta 30 Aniversario", cost: ["Rayo", "Incoloro"], damage: "130", description: "Roba 3 cartas de tu baraja." },
      { name: "Impactrueno Galáctico", cost: ["Rayo", "Rayo", "Incoloro"], damage: "260", description: "Descarta 2 Energías de este Pokémon." }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "La obra cumbre de Mitsuhiro Arita para conmemorar los 30 años de Pokémon TCG.",
    isSecret: true
  },
  {
    id: "30th-150",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "150/158",
    nameEs: "Pikachu ex (Rara Ilustración)",
    nameEn: "Pikachu ex (Illustration Rare)",
    elementType: "Rayo",
    subType: "ex",
    hp: 220,
    rarity: "Rara Ilustración",
    artist: "Naoki Saito",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-150-msyamfoi-high.webp?v=1787035210732",
    stage: "Básico",
    marketPrice: "89,00 €",
    attacks: [
      { name: "Electro Rayo Celebración", cost: ["Rayo", "Incoloro"], damage: "140", description: "" }
    ],
    weakness: "Lucha x2",
    retreatCost: 1,
    flavorText: "Pikachu desatando una tormenta eléctrica dorada.",
    isSecret: true
  },
  {
    id: "30th-157",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "157/158",
    nameEs: "Mewtwo ex (Rara Futurista por YOSHIROTTEN)",
    nameEn: "Mewtwo ex (Futuristic Rare by YOSHIROTTEN)",
    elementType: "Psíquico",
    subType: "ex",
    hp: 310,
    rarity: "Ultra Rara",
    artist: "YOSHIROTTEN",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-157-high.webp?v=1780504971133",
    stage: "Básico",
    marketPrice: "240,00 €",
    attacks: [
      { name: "Onda Psíquica Futurista", cost: ["Psíquico", "Incoloro"], damage: "120", description: "Coloca 4 contadores de daño en los Pokémon en banca del rival." },
      { name: "Psicorruptor Cuántico", cost: ["Psíquico", "Psíquico", "Incoloro"], damage: "280", description: "Descarta 2 Energías Especiales del rival." }
    ],
    weakness: "Oscura x2",
    retreatCost: 2,
    flavorText: "Nueva rareza 'Rara Futurista' diseñada por el artista vanguardista japonés YOSHIROTTEN.",
    isSecret: true
  },
  {
    id: "30th-158",
    expansionId: "30th",
    expansionCode: "30C",
    cardNumber: "158/158",
    nameEs: "Mew ex (Rara Futurista por YOSHIROTTEN)",
    nameEn: "Mew ex (Futuristic Rare by YOSHIROTTEN)",
    elementType: "Psíquico",
    subType: "ex",
    hp: 280,
    rarity: "Ultra Rara",
    artist: "YOSHIROTTEN",
    image: "https://cdn.pokedexia.com/cards/me/30C/cards/es/30c-158-high.webp?v=1780504966947",
    stage: "Básico",
    marketPrice: "290,00 €",
    attacks: [
      { name: "Habilidad: Genoma Infinito", cost: [], damage: "", description: "Mew ex puede usar cualquier ataque de los Pokémon en juego pagando el coste de Energía requerido." },
      { name: "Chispazo Dimensional", cost: ["Incoloro", "Incoloro", "Incoloro"], damage: "190", description: "Roba cartas hasta tener 6 cartas en tu mano." }
    ],
    weakness: "Oscura x2",
    retreatCost: 0,
    flavorText: "La carta más representativa de la nueva rareza 'Rara Futurista' por YOSHIROTTEN.",
    isSecret: true
  }
];

// Reemplazar ANIV30_CARDS_DATA en js/cardsData.js
let cardsCode = fs.readFileSync('js/cardsData.js', 'utf8');

const startMarker = 'const ANIV30_CARDS_DATA = [';
const endMarker = 'const PBL_CARDS_DATA = [';

const startIndex = cardsCode.indexOf(startMarker);
const endIndex = cardsCode.indexOf(endMarker);

if (startIndex !== -1 && endIndex !== -1) {
  const newChunk = `const ANIV30_CARDS_DATA = ${JSON.stringify(raw30Cards, null, 2)};\n\n// ============================================================================\n// --- COLECCIÓN 3: MEGAEVOLUCIÓN OSCURIDAD ABSOLUTA (PBL) ---\n// ============================================================================\n`;
  cardsCode = cardsCode.substring(0, startIndex) + newChunk + cardsCode.substring(endIndex);
  fs.writeFileSync('js/cardsData.js', cardsCode, 'utf8');
  console.log(`✅ ANIV30_CARDS_DATA actualizado con las ${raw30Cards.length} cartas oficiales e imágenes exactas de Pokedexia CDN.`);
} else {
  console.error('No se encontraron los marcadores en js/cardsData.js');
}
